In [1]:
import pandas as pd

In [ ]:
bmwdf = pd.read_csv('bmw.csv')
bmwdf.sh

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low
...,...,...,...,...,...,...,...,...,...,...,...
49995,i3,2014,Asia,Red,Hybrid,Manual,4.6,151030,42932,8182,High
49996,i3,2023,Middle East,Silver,Electric,Manual,4.2,147396,48714,9816,High
49997,5 Series,2010,Middle East,Red,Petrol,Automatic,4.5,174939,46126,8280,High
49998,i3,2020,Asia,White,Electric,Automatic,3.8,3379,58566,9486,High
49999,X1,2020,North America,Blue,Diesel,Manual,3.3,171003,77492,1764,Low

In [ ]:
bmwdf.loc[:,['Model', 'Year', 'Price_USD']] #: = everything. So this means "Everything" in Model, Year and Price USD columns

          Model  Year  Price_USD
0      5 Series  2016      98740
1            i8  2013      79219
2      5 Series  2022     113265
3            X3  2024      60971
4      7 Series  2020      49898
...         ...   ...        ...
49995        i3  2014      42932
49996        i3  2023      48714
49997  5 Series  2010      46126
49998        i3  2020      58566
49999        X1  2020      77492

[50000 rows x 3 columns]

In [44]:
bmwdf.set_index("Model")

,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
Model,,,,,,,,,,
5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low
...,...,...,...,...,...,...,...,...,...,...
i3,2014,Asia,Red,Hybrid,Manual,4.6,151030,42932,8182,High
i3,2023,Middle East,Silver,Electric,Manual,4.2,147396,48714,9816,High
5 Series,2010,Middle East,Red,Petrol,Automatic,4.5,174939,46126,8280,High
i3,2020,Asia,White,Electric,Automatic,3.8,3379,58566,9486,High
X1,2020,North America,Blue,Diesel,Manual,3.3,171003,77492,1764,Low

In [45]:
bmwdf

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low
...,...,...,...,...,...,...,...,...,...,...,...
49995,i3,2014,Asia,Red,Hybrid,Manual,4.6,151030,42932,8182,High
49996,i3,2023,Middle East,Silver,Electric,Manual,4.2,147396,48714,9816,High
49997,5 Series,2010,Middle East,Red,Petrol,Automatic,4.5,174939,46126,8280,High
49998,i3,2020,Asia,White,Electric,Automatic,3.8,3379,58566,9486,High
49999,X1,2020,North America,Blue,Diesel,Manual,3.3,171003,77492,1764,Low

In [49]:
filter_year = bmwdf[bmwdf['Year'] >= 2024]
print(filter_year)

          Model  Year         Region   Color Fuel_Type Transmission  \
3            X3  2024    Middle East    Blue    Petrol    Automatic
40           i3  2024    Middle East     Red    Petrol    Automatic
44           X5  2024  South America   Black    Hybrid       Manual
47     5 Series  2024           Asia    Blue  Electric       Manual
74           X1  2024         Europe     Red    Petrol    Automatic
...         ...   ...            ...     ...       ...          ...
49928        X3  2024  South America    Blue  Electric    Automatic
49942  3 Series  2024         Europe  Silver    Hybrid    Automatic
49954        M3  2024         Africa    Blue  Electric    Automatic
49968        X3  2024         Europe   White    Petrol       Manual
49982        M3  2024           Asia  Silver    Hybrid    Automatic

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification
3                1.7       27255      60971          4047                  Low
40               3.5      135958      69578           173                  Low
44               3.6      111661      82675          2155                  Low
47               3.7      157789      86855           648                  Low
74               2.7       24141      84346          4289                  Low
...              ...         ...        ...           ...                  ...
49928            2.6       11446      51398          5395                  Low
49942            1.9       76618      92351          4427                  Low
49954            2.8       86228      38003          5911                  Low
49968            2.8       44683      33558          2601                  Low
49982            1.7      198846      85034          7888                 High

[3427 rows x 11 columns]